checkpoint: "weights/sam2_hiera_tiny.pt"
model: "hfunet_hiera_tiny"

# checkpoint: "weights/mobile_sam.pt"
# model: "hfunet_tiny_vit"


# Baseline models
# model: PAN
wandb_project_name: "glas"
deep_supervision: True

dataset:
  name: glas
  root: ./datasets/GlasDataset
  image_size: 512
  split: 0.24  # training split
  seed: 42
  batch_size: 2
  num_workers: 2
  num_classes: 2 

max_epochs: 1000
save_path: checkpoints/hfunet_hiera_tiny/Glas20


# segmentation_models.pytorch specific configs
encoder_name: "resnext50_32x4d"
encoder_weights: "imagenet"
classes: 1
in_channels: 3


test_config:
  name: glas_test_dataset
  root:  ./datasets/GlasDataset
  image_size: 512
  checkpoint_path: checkpoints/hfunet_hiera_tiny/Glas20/model_epoch=239-val_dice=0.82.ckpt